-name: install rabbitmq-server -y
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

-name: sytemctl enable rabbitmq-server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    enabled: yes
    state: restarted

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

