-name: import nodjs coommon tasks 
  ansible.builtin.import_role:
    name : common
    tasks_from : nodjs 

-name : copy mongodb repo file 
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

-name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state : insatlled

-name : load master data 
   ansible.builtin.shell :
   community.mongodb.mongodb_shell:
     file: "/app/db/master-data.js"
      idempotent: yes
