-name: create appplication user 
   ansible .builtin.user:
     name: roboshop
    

-name: remove application directory 
     ansiible.builtin.file:
     path: /app
      state: absent

-name : create application directory 
   ansible.builtin.file:
      Path: / app
      state: directory
  
 - name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes   

    