- name: disable default nodejs version
  ansible.builtin.shell:  dnf module disbale nodejs -y
   

- name: enable nodejs 20 version 
   ansible.builtin.shell: dnf module enable nodejs:20 -y
    
-name: install node js 
ansible.builtin.dnf:
  name : node js 
   state : insatalled 
    

     
-name : import app preq
  ansible.builtin.include_tasks:
    file: apppreq.yml


 -name: install nodejs dependencies 
    community.general.npm:
     name: npm 
     path: /app

 -name : import systemd 
  ansible.builtin.include_tasks:
    file: systemd.yml      