-name: setup systemd service file
     ansible.builtin.copy:
      Src: "{{ app_name }}.service"
      dest: /etc/systemd/system/{{app_name}}.service

-name: start application 
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
     enabled: true
     daemon_reload: true
```