-name: install go lang
  ansible.builtin.dnf:
    name: golang
    state: insatlled 
  
-name: import  app prerequisites
  ansible.builtin.include_tasks:
     file : app-prereq.yml
  

-- name: Install Go dependencies and build the application
  ansible.builtin.shell: |
    go get -d -v ./...
    go build -o {{ app_name }}
  args:
    chdir: /app

-name: SystemD Service Setup
  ansible.builtin.include_tasks:
    file: systemd.yml